# -*- coding: utf-8 -*-
"""ex no 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146Uy6DwhGj_4zIISa8U4_bM6InqBuxEi
"""

# Importing required libraries
import numpy as np
from scipy import stats

# Sample size
N = 10

# Gaussian distributed data
# mean = 2, variance = 1
x = np.random.randn(N) + 2

# mean = 0, variance = 1
y = np.random.randn(N)

# Calculate sample variance (ddof=1 for unbiased estimate)
var_x = x.var(ddof=1)
var_y = y.var(ddof=1)

# Pooled Standard Deviation
SD = np.sqrt((var_x + var_y) / 2)

print("Standard Deviation =", SD)

# Calculate t-statistic manually
tval = (x.mean() - y.mean()) / (SD * np.sqrt(2 / N))

# Degrees of freedom
dof = 2 * N - 2

# Two-tailed p-value
pval = 2 * (1 - stats.t.cdf(abs(tval), df=dof))

print("Manual Calculation")
print("t =", tval)
print("p =", pval)

# Cross-check using scipy built-in function
tval2, pval2 = stats.ttest_ind(x, y)

print("\nUsing scipy function")
print("t =", tval2)
print("p =", pval2)